### PR TITLE
Refactor and fix install_ubuntu.sh

### LINKED ISSUE #94: polybar.py little bug
Hey, I just saw you have an error in your polybar.py file on line 89/90.

this
```python
 FileUtils.replace_line(configuration.polybar_config, 'format-connected-foreground',
                                   'format-connected-foreground = ' + self.format_con_back)
```
should be 
```python
 FileUtils.replace_line(configuration.polybar_config, 'format-connected-foreground',
                                   'format-connected-foreground = ' + self.format_con_fore)
```

:)

### PR DESCRIPTION
**Pull request by JohannesPertl**
Similar to pull request #91, I refactored install_ubuntu.sh into functions.
I added some missing dependencies, changed python to python3 and added compton. 

I also fixed #94

### CODE REVIEW

**Comment by unix121** [comment]
Hello sir, I did a quick review and it seems fine to me. I will merge it in the following days.

Have you done some testing (maybe a test run on a VM) to ensure that it works fine?

**Comment by JohannesPertl** [comment]
Yes, I used it on a fresh Ubuntu desktop and server install (server has some extra dependencies)

**Comment by unix121** [comment]
That's great, I will give it a test in the following days and merge it as soon as possible.

**Comment by unix121** [comment]
I did a test run myself, it seems fine to me. Thanks for the contribution sir.

**Pull request merged**
